RNN Part 2
SimpleRNN, Long Short Term Memory (LSTM) and Gated Recurrent Unit (GRU)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving quote_dataset.csv to quote_dataset.csv

In [4]:
import numpy as np
import matplotlib.pyplot as mat
import pandas as pd
import seaborn as sns

I will perform RNN in whole text dataframe this time.

In [5]:
df= pd.read_csv('quote_dataset.csv')

In [6]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [7]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Model
from keras.layers import Input, Dense, Dropout, Embedding, SimpleRNN, LSTM, GRU
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

In [8]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [68]:
df["quote"] [0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [69]:
df.shape

(3025, 2)

Data Cleaning (Converting all the texts into lower case and removing all the punctuations)

In [9]:
quotes= quotes.str.lower()
import string
quotes = quotes.str.translate(str.maketrans('', '', string.punctuation))
quotes = quotes.str.replace(r"[“”‘’]", "", regex=True)
quotes.head()

0    the world as we have created it is a process o...
1    it is our choices harry that show what we trul...
2    there are only two ways to live your life one ...
3    the person be it gentleman or lady who has not...
4    imperfection is beauty madness is genius and i...
Name: quote, dtype: object

In [10]:
vocab_size= 10000
tokenizer= Tokenizer(num_words= vocab_size, oov_token= 'OOV')
tokenizer.fit_on_texts(quotes)

In order to guess the vocab_size, I will find the number of unique words in the dataset.

8472

[('OOV', 1),
 ('the', 2),
 ('you', 3),
 ('to', 4),
 ('and', 5),
 ('a', 6),
 ('i', 7),
 ('is', 8),
 ('of', 9),
 ('that', 10)]

In [12]:
sequences= tokenizer.texts_to_sequences(quotes)

In [70]:
for i in range(3):
    print(quotes[i])
    print(sequences[i])

the world as we have created it is a process of our thinking it cannot be changed without changing our thinking
[2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286, 11, 147, 13, 802, 106, 742, 71, 286]
it is our choices harry that show what we truly are far more than our abilities
[11, 8, 71, 861, 374, 10, 435, 22, 20, 466, 15, 297, 53, 55, 71, 2402]
there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle
[43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96, 8, 6, 1027, 2, 103, 8, 30, 321, 129, 8, 6, 1027]

Create multiple sequences/ sequence from multiple words

In [13]:
X= []
y= []
for seq in sequences:
    for i in range(1, len(seq)):
        input_seq= seq[:i]
        output_seq= seq[i]
        X.append(input_seq)
        y.append(output_seq)

In [71]:
X

[[2],
 [2, 63],
 [2, 63, 30],
 [2, 63, 30, 20],
 [2, 63, 30, 20, 17],
 [2, 63, 30, 20, 17, 934],
 [2, 63, 30, 20, 17, 934, 11],
 [2, 63, 30, 20, 17, 934, 11, 8],
 [2, 63, 30, 20, 17, 934, 11, 8, 6],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286, 11],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286, 11, 147],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286, 11, 147, 13],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286, 11, 147, 13, 802],
 [2, 63, 30, 20, 17, 934, 11, 8, 6, 1138, 9, 71, 286, 11, 147, 13, 802, 106],
 [2,
  63,
  30,
  20,
  17,
  934,
  11,
  8,
  6,
  1138,
  9,
  71,
  286,
  11,
  147,
  13,
  802,
  106,
  742],
 [2,
  63,
  30,
  20,
  17,
  934,
  11,
  8,
  6,
  1138,
  9,
  71,
  286,
  11,
  147,
  13,
  802,
  106,
  742,
  71],
 [11],
 [11, 8],
 [11, 8, 71],
 [11, 8, 71, 861],
 [11, 8, 71, 861, 374],
 [11, 8, 71, 861, 374, 10],
 [11, 8, 71, 861, 374, 10, 435],
 [11, 8, 71, 861, 374, 10, 435, 22],
 [11, 8, 71, 861, 374, 10, 435, 22, 20],
 [11, 8, 71, 861, 374, 10, 435, 22, 20, 466],
 [11, 8, 71, 861, 374, 10, 435, 22, 20, 466, 15],
 [11, 8, 71, 861, 374, 10, 435, 22, 20, 466, 15, 297],
 [11, 8, 71, 861, 374, 10, 435, 22, 20, 466, 15, 297, 53],
 [11, 8, 71, 861, 374, 10, 435, 22, 20, 466, 15, 297, 53, 55],
 [11, 8, 71, 861, 374, 10, 435, 22, 20, 466, 15, 297, 53, 55, 71],
 [43],
 [43, 15],
 [43, 15, 54],
 [43, 15, 54, 202],
 [43, 15, 54, 202, 707],
 [43, 15, 54, 202, 707, 4],
 [43, 15, 54, 202, 707, 4, 82],
 [43, 15, 54, 202, 707, 4, 82, 16],
 [43, 15, 54, 202, 707, 4, 82, 16, 37],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96, 8],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96, 8, 6],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96, 8, 6, 1027],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96, 8, 6, 1027, 2],
 [43, 15, 54, 202, 707, 4, 82, 16, 37, 38, 8, 30, 321, 96, 8, 6, 1027, 2, 103],
 [43,
  15,
  54,
  202,
  707,
  4,
  82,
  16,
  37,
  38,
  8,
  30,
  321,
  96,
  8,
  6,
  1027,
  2,
  103,
  8],
 [43,
  15,
  54,
  202,
  707,
  4,
  82,
  16,
  37,
  38,
  8,
  30,
  321,
  96,
  8,
  6,
  1027,
  2,
  103,
  8,
  30],
 [43,
  15,
  54,
  202,
  707,
  4,
  82,
  16,
  37,
  38,
  8,
  30,
  321,
  96,
  8,
  6,
  1027,
  2,
  103,
  8,
  30,
  321],
 [43,
  15,
  54,
  202,
  707,
  4,
  82,
  16,
  37,
  38,
  8,
  30,
  321,
  96,
  8,
  6,
  1027,
  2,
  103,
  8,
  30,
  321,
  129],
 [43,
  15,
  54,
  202,
  707,
  4,
  82,
  16,
  37,
  38,
  8,
  30,
  321,
  96,
  8,
  6,
  1027,
  2,
  103,
  8,
  30,
  321,
  129,
  8],
 [43,
  15,
  54,
  202,
  707,
  4,
  82,
  16,
  37,
  38,
  8,
  30,
  321,
  96,
  8,
  6,
  1027,
  2,
  103,
  8,
  30,
  321,
  129,
  8,
  6],
 [2],
 [2, 117],
 [2, 117, 13],
 [2, 117, 13, 11],
 [2, 117, 13, 11, 2403],
 [2, 117, 13, 11, 2403, 33],
 [2, 117, 13, 11, 2403, 33, 1028],
 [2, 117, 13, 11, 2403, 33, 1028, 32],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599, 12],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599, 12, 6],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599, 12, 6, 75],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599, 12, 6, 75, 1313],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599, 12, 6, 75, 1313, 121],
 [2, 117, 13, 11, 2403, 33, 1028, 32, 83, 14, 599, 12, 6, 75, 1313, 121, 13],
 [2,
  117,
  13,
  11,
  2403,
  33,
  1028,
  32,
  83,
  14,
  599,
  12,
  6,
  75,
  1313,
  121,
  13,
  2404],
 [2405],
 [2405, 8],
 [2405, 8, 307],
 [2405, 8, 307, 743],
 [2405, 8, 307, 743, 8],
 [2405, 8, 307, 743, 8, 637],
 [2405, 8, 307, 743, 8, 637, 5],
 [2405, 8, 307, 743, 8, 637, 5, 40],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145, 4],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145, 4, 13],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145, 4, 13, 678],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145, 4, 13, 678, 1314],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145, 4, 13, 678, 1314, 55],
 [2405, 8, 307, 743, 8, 637, 5, 40, 145, 4, 13, 678, 1314, 55, 678],
 [261],
 [261, 14],
 [261, 14, 4],
 [261, 14, 4, 203],
 [261, 14, 4, 203, 6],
 [261, 14, 4, 203, 6, 93],
 [261, 14, 4, 203, 6, 93, 9],
 [261, 14, 4, 203, 6, 93, 9, 436],
 [261, 14, 4, 203, 6, 93, 9, 436, 284],
 [261, 14, 4, 203, 6, 93, 9, 436, 284, 203],
 [261, 14, 4, 203, 6, 93, 9, 436, 284, 203, 6],
 [261, 14, 4, 203, 6, 93, 9, 436, 284, 203, 6, 93],
 [261, 14, 4, 203, 6, 93, 9, 436, 284, 203, 6, 93, 9],
 [11],
 [11, 8],
 [11, 8, 145],
 [11, 8, 145, 4],
 [11, 8, 145, 4, 13],
 [11, 8, 145, 4, 13, 1315],
 [11, 8, 145, 4, 13, 1315, 18],
 [11, 8, 145, 4, 13, 1315, 18, 22],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4, 13],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4, 13, 178],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4, 13, 178, 18],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4, 13, 178, 18, 22],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4, 13, 178, 18, 22, 3],
 [11, 8, 145, 4, 13, 1315, 18, 22, 3, 15, 55, 4, 13, 178, 18, 22, 3, 15],
 [7],
 [7, 17],
 [7, 17, 14],
 [7, 17, 14, 1316],
 [7, 17, 14, 1316, 174],
 [7, 17, 14, 1316, 174, 52],
 [7, 17, 14, 1316, 174, 52, 417],
 [7, 17, 14, 1316, 174, 52, 417, 2406],
 [7, 17, 14, 1316, 174, 52, 417, 2406, 707],
 [7, 17, 14, 1316, 174, 52, 417, 2406, 707, 10],
 [7, 17, 14, 1316, 174, 52, 417, 2406, 707, 10, 313],
 [6],
 [6, 184],
 [6, 184, 8],
 [6, 184, 8, 41],
 [6, 184, 8, 41, 6],
 [6, 184, 8, 41, 6, 803],
 [6, 184, 8, 41, 6, 803, 1317],
 [6, 184, 8, 41, 6, 803, 1317, 3],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322, 11],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322, 11, 8],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322, 11, 8, 170],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322, 11, 8, 170, 40],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322, 11, 8, 170, 40, 12],
 [6, 184, 8, 41, 6, 803, 1317, 3, 48, 51, 60, 322, 11, 8, 170, 40, 12, 638],
 [6],
 [6, 112],
 [6, 112, 106],
 [6, 112, 106, 1029],
 [6, 112, 106, 1029, 8],
 [6, 112, 106, 1029, 8, 41],
 [6, 112, 106, 1029, 8, 41, 3],
 [6, 112, 106, 1029, 8, 41, 3, 51],
 [57],
 [57, 37],
 [57, 37, 8],
 [57, 37, 8, 22],
 [57, 37, 8, 22, 3],
 [57, 37, 8, 22, 3, 66],
 [57, 37, 8, 22, 3, 66, 11],
 [57, 37, 8, 22, 3, 66, 11, 49],
 [57, 37, 8, 22, 3, 66, 11, 49, 185],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133, 4],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133, 4, 745],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133, 4, 745, 59],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133, 4, 745, 59, 127],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133, 4, 745, 59, 127, 40],
 [57, 37, 8, 22, 3, 66, 11, 49, 185, 22, 86, 133, 4, 745, 59, 127, 40, 6],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3,
  148],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3,
  148,
  129],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3,
  148,
  129,
  224],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3,
  148,
  129,
  224,
  16],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3,
  148,
  129,
  224,
  16,
  162],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,
  8,
  3,
  97,
  4,
  467,
  60,
  86,
  133,
  4,
  745,
  11,
  59,
  519,
  29,
  13,
  16,
  212,
  746,
  520,
  41,
  11,
  804,
  19,
  52,
  156,
  92,
  135,
  92,
  80,
  2,
  223,
  10,
  276,
  24,
  3,
  148,
  129,
  224,
  16,
  162,
  160],
 [57,
  37,
  8,
  22,
  3,
  66,
  11,
  49,
  185,
  22,
  86,
  133,
  4,
  745,
  59,
  127,
  40,
  6,
  1895,
  177,
  19,
  2,
  75,
  211,

In [72]:
y

array([ 63,  30,  20, ...,   4, 173, 103])

In [73]:
len(X), len(y)

(84823, 84823)

In [14]:
max_length= max(len(x) for x in X)
max_length

745

In [15]:
X_pad= pad_sequences(X, maxlen= max_length, padding= "pre")
y= np.array(y)

In [74]:
X_pad.shape, y.shape

((84823, 745), (84823,))

One-Hot Encoding for y

In [16]:
y_encoded= to_categorical(y, num_classes= vocab_size)

In [17]:
X_pad.shape, y_encoded.shape

((84823, 745), (84823, 10000))

In [18]:
embed_dim= 32
rnn_units= 64

Model Creation and Training for SimpleRNN.

In [19]:
input_layer= Input(shape= (max_length,), dtype= "int32", name= "Input_Layer")
embedding_layer= Embedding(input_dim= vocab_size, output_dim= embed_dim, mask_zero= True, name= "Embedding_Layer")(input_layer)

In [20]:
rnn= SimpleRNN(units= rnn_units, return_sequences= False, return_state= False, name= "SimpleRNN_Layer")
embedding_layer_last= rnn(embedding_layer)
output_layer= Dense(units= vocab_size, activation= "softmax", name= "Output_Layer")(embedding_layer_last)

In [21]:
model= Model(inputs= input_layer, outputs= output_layer)

In [22]:
model.compile(optimizer= "adam", loss= "categorical_crossentropy", metrics= ["accuracy"])

In [27]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ Input_Layer         │ (None, 745)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Embedding_Layer     │ (None, 745, 32)   │    320,000 │ Input_Layer[0][0] │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal           │ (None, 745)       │          0 │ Input_Layer[0][0] │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ SimpleRNN_Layer     │ (None, 64)        │      6,208 │ Embedding_Layer[… │
│ (SimpleRNN)         │                   │            │ not_equal[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Output_Layer        │ (None, 10000)     │    650,000 │ SimpleRNN_Layer[… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 976,208 (3.72 MB)

 Trainable params: 976,208 (3.72 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
simple_rnn_model= model.fit(X_pad, y_encoded, epochs= 100, batch_size= 256, validation_split= 0.2, verbose= 1)

Epoch 1/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 34s 105ms/step - accuracy: 0.0380 - loss: 7.0047 - val_accuracy: 0.0373 - val_loss: 6.7388
Epoch 2/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.0391 - loss: 6.5432 - val_accuracy: 0.0375 - val_loss: 6.7637
Epoch 3/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.0457 - loss: 6.4253 - val_accuracy: 0.0545 - val_loss: 6.6801
Epoch 4/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.0598 - loss: 6.2564 - val_accuracy: 0.0668 - val_loss: 6.6041
Epoch 5/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 44s 88ms/step - accuracy: 0.0753 - loss: 6.1021 - val_accuracy: 0.0796 - val_loss: 6.5303
Epoch 6/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.0880 - loss: 5.9542 - val_accuracy: 0.0845 - val_loss: 6.4770
Epoch 7/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.1004 - loss: 5.8193 - val_accuracy: 0.0939 - val_loss: 6.4301
Epoch 8/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.1121 - loss: 5.6899 - val_accuracy: 0.0977 - val_loss: 6.3976
Epoch 9/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 42s 83ms/step - accuracy: 0.1193 - loss: 5.5792 - val_accuracy: 0.1002 - val_loss: 6.3805
Epoch 10/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.1241 - loss: 5.4827 - val_accuracy: 0.1032 - val_loss: 6.3762
Epoch 11/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.1285 - loss: 5.3978 - val_accuracy: 0.1070 - val_loss: 6.3677
Epoch 12/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - accuracy: 0.1340 - loss: 5.3194 - val_accuracy: 0.1066 - val_loss: 6.3727
Epoch 13/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.1385 - loss: 5.2457 - val_accuracy: 0.1090 - val_loss: 6.3846
Epoch 14/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.1429 - loss: 5.1760 - val_accuracy: 0.1102 - val_loss: 6.3929
Epoch 15/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 81ms/step - accuracy: 0.1474 - loss: 5.1102 - val_accuracy: 0.1101 - val_loss: 6.4125
Epoch 16/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.1525 - loss: 5.0474 - val_accuracy: 0.1103 - val_loss: 6.4300
Epoch 17/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.1558 - loss: 4.9861 - val_accuracy: 0.1107 - val_loss: 6.4359
Epoch 18/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 83ms/step - accuracy: 0.1607 - loss: 4.9270 - val_accuracy: 0.1100 - val_loss: 6.4661
Epoch 19/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 24s 90ms/step - accuracy: 0.1654 - loss: 4.8706 - val_accuracy: 0.1103 - val_loss: 6.4819
Epoch 20/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.1700 - loss: 4.8160 - val_accuracy: 0.1098 - val_loss: 6.5056
Epoch 21/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 78ms/step - accuracy: 0.1733 - loss: 4.7611 - val_accuracy: 0.1099 - val_loss: 6.5148
Epoch 22/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 47s 103ms/step - accuracy: 0.1779 - loss: 4.7087 - val_accuracy: 0.1099 - val_loss: 6.5323
Epoch 23/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 25s 93ms/step - accuracy: 0.1831 - loss: 4.6572 - val_accuracy: 0.1108 - val_loss: 6.5568
Epoch 24/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - accuracy: 0.1867 - loss: 4.6068 - val_accuracy: 0.1094 - val_loss: 6.5843
Epoch 25/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 39s 79ms/step - accuracy: 0.1911 - loss: 4.5576 - val_accuracy: 0.1091 - val_loss: 6.6085
Epoch 26/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.1956 - loss: 4.5092 - val_accuracy: 0.1099 - val_loss: 6.6394
Epoch 27/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 42s 83ms/step - accuracy: 0.1993 - loss: 4.4614 - val_accuracy: 0.1096 - val_loss: 6.6510
Epoch 28/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2047 - loss: 4.4152 - val_accuracy: 0.1089 - val_loss: 6.6867
Epoch 29/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 26s 96ms/step - accuracy: 0.2081 - loss: 4.3706 - val_accuracy: 0.1082 - val_loss: 6.7110
Epoch 30/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 24s 90ms/step - accuracy: 0.2137 - loss: 4.3256 - val_accuracy: 0.1086 - val_loss: 6.7384
Epoch 31/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2183 - loss: 4.2820 - val_accuracy: 0.1069 - val_loss: 6.7572
Epoch 32/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.2226 - loss: 4.2397 - val_accuracy: 0.1084 - val_loss: 6.7897
Epoch 33/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2272 - loss: 4.1977 - val_accuracy: 0.1069 - val_loss: 6.8126
Epoch 34/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.2325 - loss: 4.1570 - val_accuracy: 0.1059 - val_loss: 6.8343
Epoch 35/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.2379 - loss: 4.1165 - val_accuracy: 0.1057 - val_loss: 6.8664
Epoch 36/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2412 - loss: 4.0779 - val_accuracy: 0.1051 - val_loss: 6.8893
Epoch 37/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2454 - loss: 4.0398 - val_accuracy: 0.1044 - val_loss: 6.9186
Epoch 38/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2500 - loss: 4.0024 - val_accuracy: 0.1052 - val_loss: 6.9402
Epoch 39/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.2562 - loss: 3.9662 - val_accuracy: 0.1038 - val_loss: 6.9745
Epoch 40/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2584 - loss: 3.9310 - val_accuracy: 0.1023 - val_loss: 6.9921
Epoch 41/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.2643 - loss: 3.8962 - val_accuracy: 0.1013 - val_loss: 7.0227
Epoch 42/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2693 - loss: 3.8618 - val_accuracy: 0.1011 - val_loss: 7.0462
Epoch 43/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.2728 - loss: 3.8297 - val_accuracy: 0.1001 - val_loss: 7.0661
Epoch 44/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2776 - loss: 3.7973 - val_accuracy: 0.1014 - val_loss: 7.0917
Epoch 45/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2827 - loss: 3.7652 - val_accuracy: 0.1024 - val_loss: 7.1186
Epoch 46/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2847 - loss: 3.7352 - val_accuracy: 0.0989 - val_loss: 7.1391
Epoch 47/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2900 - loss: 3.7059 - val_accuracy: 0.1000 - val_loss: 7.1627
Epoch 48/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.2942 - loss: 3.6771 - val_accuracy: 0.0977 - val_loss: 7.1861
Epoch 49/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.2974 - loss: 3.6478 - val_accuracy: 0.0993 - val_loss: 7.2053
Epoch 50/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.3013 - loss: 3.6200 - val_accuracy: 0.0984 - val_loss: 7.2391
Epoch 51/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3053 - loss: 3.5931 - val_accuracy: 0.0950 - val_loss: 7.2619
Epoch 52/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - accuracy: 0.3091 - loss: 3.5672 - val_accuracy: 0.0940 - val_loss: 7.2871
Epoch 53/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3131 - loss: 3.5409 - val_accuracy: 0.0954 - val_loss: 7.3019
Epoch 54/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3164 - loss: 3.5160 - val_accuracy: 0.0961 - val_loss: 7.3163
Epoch 55/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3200 - loss: 3.4920 - val_accuracy: 0.0949 - val_loss: 7.3434
Epoch 56/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.3239 - loss: 3.4678 - val_accuracy: 0.0946 - val_loss: 7.3694
Epoch 57/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3279 - loss: 3.4436 - val_accuracy: 0.0949 - val_loss: 7.3894
Epoch 58/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3307 - loss: 3.4210 - val_accuracy: 0.0954 - val_loss: 7.4010
Epoch 59/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3338 - loss: 3.3995 - val_accuracy: 0.0938 - val_loss: 7.4330
Epoch 60/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.3376 - loss: 3.3777 - val_accuracy: 0.0930 - val_loss: 7.4579
Epoch 61/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.3405 - loss: 3.3569 - val_accuracy: 0.0934 - val_loss: 7.4719
Epoch 62/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3449 - loss: 3.3373 - val_accuracy: 0.0924 - val_loss: 7.4961
Epoch 63/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3471 - loss: 3.3155 - val_accuracy: 0.0937 - val_loss: 7.5154
Epoch 64/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3496 - loss: 3.2973 - val_accuracy: 0.0908 - val_loss: 7.5438
Epoch 65/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3529 - loss: 3.2779 - val_accuracy: 0.0920 - val_loss: 7.5554
Epoch 66/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3560 - loss: 3.2589 - val_accuracy: 0.0930 - val_loss: 7.5773
Epoch 67/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.3585 - loss: 3.2406 - val_accuracy: 0.0917 - val_loss: 7.5975
Epoch 68/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3614 - loss: 3.2236 - val_accuracy: 0.0912 - val_loss: 7.6190
Epoch 69/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3643 - loss: 3.2061 - val_accuracy: 0.0925 - val_loss: 7.6291
Epoch 70/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3666 - loss: 3.1883 - val_accuracy: 0.0905 - val_loss: 7.6556
Epoch 71/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3682 - loss: 3.1719 - val_accuracy: 0.0918 - val_loss: 7.6696
Epoch 72/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 79ms/step - accuracy: 0.3712 - loss: 3.1550 - val_accuracy: 0.0917 - val_loss: 7.6914
Epoch 73/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3731 - loss: 3.1404 - val_accuracy: 0.0902 - val_loss: 7.7064
Epoch 74/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3777 - loss: 3.1235 - val_accuracy: 0.0901 - val_loss: 7.7263
Epoch 75/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 78ms/step - accuracy: 0.3777 - loss: 3.1095 - val_accuracy: 0.0887 - val_loss: 7.7596
Epoch 76/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3810 - loss: 3.0948 - val_accuracy: 0.0878 - val_loss: 7.7678
Epoch 77/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3836 - loss: 3.0787 - val_accuracy: 0.0888 - val_loss: 7.7932
Epoch 78/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3849 - loss: 3.0643 - val_accuracy: 0.0888 - val_loss: 7.8073
Epoch 79/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.3881 - loss: 3.0515 - val_accuracy: 0.0881 - val_loss: 7.8305
Epoch 80/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.3899 - loss: 3.0362 - val_accuracy: 0.0898 - val_loss: 7.8333
Epoch 81/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 78ms/step - accuracy: 0.3907 - loss: 3.0224 - val_accuracy: 0.0879 - val_loss: 7.8558
Epoch 82/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3928 - loss: 3.0128 - val_accuracy: 0.0869 - val_loss: 7.8769
Epoch 83/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3938 - loss: 2.9985 - val_accuracy: 0.0866 - val_loss: 7.8969
Epoch 84/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3971 - loss: 2.9878 - val_accuracy: 0.0875 - val_loss: 7.9092
Epoch 85/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3986 - loss: 2.9725 - val_accuracy: 0.0861 - val_loss: 7.9326
Epoch 86/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.4006 - loss: 2.9614 - val_accuracy: 0.0882 - val_loss: 7.9387
Epoch 87/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.4028 - loss: 2.9503 - val_accuracy: 0.0869 - val_loss: 7.9559
Epoch 88/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.4054 - loss: 2.9364 - val_accuracy: 0.0881 - val_loss: 7.9697
Epoch 89/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.4057 - loss: 2.9260 - val_accuracy: 0.0849 - val_loss: 7.9843
Epoch 90/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.4077 - loss: 2.9191 - val_accuracy: 0.0871 - val_loss: 8.0068
Epoch 91/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.4101 - loss: 2.9037 - val_accuracy: 0.0854 - val_loss: 8.0280
Epoch 92/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - accuracy: 0.4119 - loss: 2.8952 - val_accuracy: 0.0866 - val_loss: 8.0442
Epoch 93/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 40s 79ms/step - accuracy: 0.4139 - loss: 2.8834 - val_accuracy: 0.0849 - val_loss: 8.0453
Epoch 94/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.4140 - loss: 2.8727 - val_accuracy: 0.0865 - val_loss: 8.0682
Epoch 95/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4164 - loss: 2.8631 - val_accuracy: 0.0853 - val_loss: 8.0774
Epoch 96/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4173 - loss: 2.8545 - val_accuracy: 0.0853 - val_loss: 8.0962
Epoch 97/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.4199 - loss: 2.8423 - val_accuracy: 0.0849 - val_loss: 8.1198
Epoch 98/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.4204 - loss: 2.8346 - val_accuracy: 0.0852 - val_loss: 8.1222
Epoch 99/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.4239 - loss: 2.8221 - val_accuracy: 0.0843 - val_loss: 8.1532
Epoch 100/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.4236 - loss: 2.8149 - val_accuracy: 0.0853 - val_loss: 8.1654

For deep learning, I should save HDF5 file instead of pickel file.

In [30]:
model.save('simple_rnn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model Creation and Training for LSTM.

In [23]:
input_layer2= Input(shape= (max_length,), dtype= "int32", name= "Input_Layer2")
embedding_layer2= Embedding(input_dim= vocab_size, output_dim= embed_dim, mask_zero= False, name= "Embedding_Layer2")(input_layer2)

In [24]:
rnn2= LSTM(units= rnn_units, return_sequences= False, return_state= False, name= "LSTM_Layer")
embedding_layer_last2= rnn2(embedding_layer2)
output_layer2= Dense(units= vocab_size, activation= "softmax", name= "Output_Layer2")(embedding_layer_last2)

In [25]:
model2= Model(inputs= input_layer2, outputs= output_layer2)

In [26]:
model2.compile(optimizer= "adam", loss= "categorical_crossentropy", metrics= ["accuracy"])

In [27]:
model2.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Input_Layer2 (InputLayer)       │ (None, 745)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Embedding_Layer2 (Embedding)    │ (None, 745, 32)        │       320,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ LSTM_Layer (LSTM)               │ (None, 64)             │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer2 (Dense)           │ (None, 10000)          │       650,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 994,832 (3.79 MB)

 Trainable params: 994,832 (3.79 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
lstm_model= model2.fit(X_pad, y_encoded, epochs= 100, batch_size= 256, validation_split= 0.2, verbose= 1)

Epoch 1/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 60ms/step - accuracy: 0.0387 - loss: 6.9390 - val_accuracy: 0.0373 - val_loss: 6.6144
Epoch 2/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.0391 - loss: 6.4188 - val_accuracy: 0.0373 - val_loss: 6.6406
Epoch 3/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.0441 - loss: 6.3369 - val_accuracy: 0.0463 - val_loss: 6.6402
Epoch 4/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.0487 - loss: 6.2548 - val_accuracy: 0.0523 - val_loss: 6.6135
Epoch 5/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.0550 - loss: 6.1740 - val_accuracy: 0.0582 - val_loss: 6.5670
Epoch 6/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.0654 - loss: 6.0921 - val_accuracy: 0.0617 - val_loss: 6.5388
Epoch 7/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.0732 - loss: 6.0150 - val_accuracy: 0.0714 - val_loss: 6.5090
Epoch 8/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 55ms/step - accuracy: 0.0815 - loss: 5.9373 - val_accuracy: 0.0805 - val_loss: 6.4962
Epoch 9/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.0919 - loss: 5.8579 - val_accuracy: 0.0852 - val_loss: 6.4713
Epoch 10/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 61ms/step - accuracy: 0.0999 - loss: 5.7808 - val_accuracy: 0.0882 - val_loss: 6.4601
Epoch 11/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - accuracy: 0.1051 - loss: 5.7094 - val_accuracy: 0.0900 - val_loss: 6.4685
Epoch 12/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1095 - loss: 5.6450 - val_accuracy: 0.0926 - val_loss: 6.4839
Epoch 13/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1145 - loss: 5.5838 - val_accuracy: 0.0951 - val_loss: 6.4933
Epoch 14/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.1175 - loss: 5.5265 - val_accuracy: 0.0963 - val_loss: 6.4987
Epoch 15/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1216 - loss: 5.4703 - val_accuracy: 0.0974 - val_loss: 6.5100
Epoch 16/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 56ms/step - accuracy: 0.1246 - loss: 5.4151 - val_accuracy: 0.0993 - val_loss: 6.5174
Epoch 17/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.1270 - loss: 5.3605 - val_accuracy: 0.0991 - val_loss: 6.5204
Epoch 18/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 75ms/step - accuracy: 0.1297 - loss: 5.3057 - val_accuracy: 0.1014 - val_loss: 6.5307
Epoch 19/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.1332 - loss: 5.2531 - val_accuracy: 0.1024 - val_loss: 6.5405
Epoch 20/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 70ms/step - accuracy: 0.1356 - loss: 5.2019 - val_accuracy: 0.1050 - val_loss: 6.5469
Epoch 21/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 61ms/step - accuracy: 0.1384 - loss: 5.1530 - val_accuracy: 0.1072 - val_loss: 6.5577
Epoch 22/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1411 - loss: 5.1049 - val_accuracy: 0.1063 - val_loss: 6.5731
Epoch 23/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1441 - loss: 5.0602 - val_accuracy: 0.1088 - val_loss: 6.5942
Epoch 24/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1466 - loss: 5.0159 - val_accuracy: 0.1075 - val_loss: 6.6121
Epoch 25/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.1486 - loss: 4.9717 - val_accuracy: 0.1085 - val_loss: 6.6158
Epoch 26/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 63ms/step - accuracy: 0.1510 - loss: 4.9289 - val_accuracy: 0.1106 - val_loss: 6.6364
Epoch 27/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 58ms/step - accuracy: 0.1543 - loss: 4.8867 - val_accuracy: 0.1096 - val_loss: 6.6617
Epoch 28/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.1568 - loss: 4.8465 - val_accuracy: 0.1113 - val_loss: 6.6777
Epoch 29/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 55ms/step - accuracy: 0.1605 - loss: 4.8056 - val_accuracy: 0.1119 - val_loss: 6.6923
Epoch 30/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1626 - loss: 4.7655 - val_accuracy: 0.1125 - val_loss: 6.7216
Epoch 31/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.1640 - loss: 4.7272 - val_accuracy: 0.1122 - val_loss: 6.7359
Epoch 32/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1662 - loss: 4.6883 - val_accuracy: 0.1119 - val_loss: 6.7592
Epoch 33/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1692 - loss: 4.6504 - val_accuracy: 0.1109 - val_loss: 6.7787
Epoch 34/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.1717 - loss: 4.6137 - val_accuracy: 0.1109 - val_loss: 6.8060
Epoch 35/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1740 - loss: 4.5772 - val_accuracy: 0.1113 - val_loss: 6.8237
Epoch 36/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1769 - loss: 4.5416 - val_accuracy: 0.1114 - val_loss: 6.8502
Epoch 37/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.1804 - loss: 4.5071 - val_accuracy: 0.1096 - val_loss: 6.8732
Epoch 38/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1832 - loss: 4.4730 - val_accuracy: 0.1112 - val_loss: 6.9013
Epoch 39/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 57ms/step - accuracy: 0.1866 - loss: 4.4395 - val_accuracy: 0.1105 - val_loss: 6.9237
Epoch 40/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - accuracy: 0.1905 - loss: 4.4070 - val_accuracy: 0.1111 - val_loss: 6.9478
Epoch 41/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1926 - loss: 4.3746 - val_accuracy: 0.1108 - val_loss: 6.9748
Epoch 42/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 58ms/step - accuracy: 0.1971 - loss: 4.3423 - val_accuracy: 0.1113 - val_loss: 7.0004
Epoch 43/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1999 - loss: 4.3118 - val_accuracy: 0.1122 - val_loss: 7.0239
Epoch 44/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2036 - loss: 4.2817 - val_accuracy: 0.1112 - val_loss: 7.0498
Epoch 45/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2070 - loss: 4.2518 - val_accuracy: 0.1113 - val_loss: 7.0782
Epoch 46/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2102 - loss: 4.2236 - val_accuracy: 0.1102 - val_loss: 7.1076
Epoch 47/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.2132 - loss: 4.1943 - val_accuracy: 0.1101 - val_loss: 7.1312
Epoch 48/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 59ms/step - accuracy: 0.2168 - loss: 4.1673 - val_accuracy: 0.1100 - val_loss: 7.1594
Epoch 49/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.2209 - loss: 4.1400 - val_accuracy: 0.1091 - val_loss: 7.1842
Epoch 50/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.2251 - loss: 4.1126 - val_accuracy: 0.1086 - val_loss: 7.2136
Epoch 51/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.2280 - loss: 4.0882 - val_accuracy: 0.1088 - val_loss: 7.2391
Epoch 52/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 67ms/step - accuracy: 0.2310 - loss: 4.0629 - val_accuracy: 0.1076 - val_loss: 7.2667
Epoch 53/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 65ms/step - accuracy: 0.2342 - loss: 4.0391 - val_accuracy: 0.1067 - val_loss: 7.2931
Epoch 54/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.2367 - loss: 4.0149 - val_accuracy: 0.1078 - val_loss: 7.3205
Epoch 55/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2400 - loss: 3.9905 - val_accuracy: 0.1076 - val_loss: 7.3460
Epoch 56/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 55ms/step - accuracy: 0.2435 - loss: 3.9676 - val_accuracy: 0.1070 - val_loss: 7.3769
Epoch 57/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.2465 - loss: 3.9440 - val_accuracy: 0.1059 - val_loss: 7.3991
Epoch 58/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2489 - loss: 3.9230 - val_accuracy: 0.1054 - val_loss: 7.4289
Epoch 59/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.2532 - loss: 3.9008 - val_accuracy: 0.1060 - val_loss: 7.4596
Epoch 60/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.2551 - loss: 3.8804 - val_accuracy: 0.1056 - val_loss: 7.4847
Epoch 61/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 67ms/step - accuracy: 0.2580 - loss: 3.8584 - val_accuracy: 0.1067 - val_loss: 7.5055
Epoch 62/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 55ms/step - accuracy: 0.2612 - loss: 3.8389 - val_accuracy: 0.1052 - val_loss: 7.5347
Epoch 63/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2641 - loss: 3.8185 - val_accuracy: 0.1061 - val_loss: 7.5628
Epoch 64/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.2660 - loss: 3.7993 - val_accuracy: 0.1066 - val_loss: 7.5937
Epoch 65/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.2685 - loss: 3.7802 - val_accuracy: 0.1067 - val_loss: 7.6143
Epoch 66/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2718 - loss: 3.7601 - val_accuracy: 0.1059 - val_loss: 7.6442
Epoch 67/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.2739 - loss: 3.7422 - val_accuracy: 0.1050 - val_loss: 7.6644
Epoch 68/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.2765 - loss: 3.7235 - val_accuracy: 0.1041 - val_loss: 7.6923
Epoch 69/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.2790 - loss: 3.7059 - val_accuracy: 0.1040 - val_loss: 7.7162
Epoch 70/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2828 - loss: 3.6876 - val_accuracy: 0.1050 - val_loss: 7.7348
Epoch 71/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2844 - loss: 3.6704 - val_accuracy: 0.1036 - val_loss: 7.7655
Epoch 72/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.2879 - loss: 3.6528 - val_accuracy: 0.1054 - val_loss: 7.7905
Epoch 73/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.2896 - loss: 3.6380 - val_accuracy: 0.1025 - val_loss: 7.8162
Epoch 74/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2931 - loss: 3.6202 - val_accuracy: 0.1045 - val_loss: 7.8317
Epoch 75/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2957 - loss: 3.6028 - val_accuracy: 0.1010 - val_loss: 7.8622
Epoch 76/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2975 - loss: 3.5872 - val_accuracy: 0.1026 - val_loss: 7.8924
Epoch 77/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.2998 - loss: 3.5717 - val_accuracy: 0.1039 - val_loss: 7.9133
Epoch 78/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.3021 - loss: 3.5563 - val_accuracy: 0.1030 - val_loss: 7.9289
Epoch 79/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 58ms/step - accuracy: 0.3057 - loss: 3.5399 - val_accuracy: 0.1030 - val_loss: 7.9570
Epoch 80/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 79ms/step - accuracy: 0.3077 - loss: 3.5254 - val_accuracy: 0.1003 - val_loss: 7.9851
Epoch 81/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.3101 - loss: 3.5112 - val_accuracy: 0.1011 - val_loss: 8.0080
Epoch 82/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 77ms/step - accuracy: 0.3125 - loss: 3.4955 - val_accuracy: 0.1029 - val_loss: 8.0223
Epoch 83/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.3138 - loss: 3.4798 - val_accuracy: 0.1023 - val_loss: 8.0427
Epoch 84/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - accuracy: 0.3159 - loss: 3.4671 - val_accuracy: 0.1011 - val_loss: 8.0732
Epoch 85/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.3186 - loss: 3.4524 - val_accuracy: 0.1022 - val_loss: 8.0948
Epoch 86/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 23s 68ms/step - accuracy: 0.3208 - loss: 3.4384 - val_accuracy: 0.1007 - val_loss: 8.1145
Epoch 87/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 56ms/step - accuracy: 0.3229 - loss: 3.4240 - val_accuracy: 0.1004 - val_loss: 8.1360
Epoch 88/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 24s 68ms/step - accuracy: 0.3251 - loss: 3.4098 - val_accuracy: 0.1009 - val_loss: 8.1577
Epoch 89/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 56ms/step - accuracy: 0.3264 - loss: 3.3968 - val_accuracy: 0.1011 - val_loss: 8.1843
Epoch 90/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.3291 - loss: 3.3837 - val_accuracy: 0.1001 - val_loss: 8.2061
Epoch 91/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 67ms/step - accuracy: 0.3303 - loss: 3.3705 - val_accuracy: 0.1003 - val_loss: 8.2286
Epoch 92/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 65ms/step - accuracy: 0.3327 - loss: 3.3578 - val_accuracy: 0.1014 - val_loss: 8.2411
Epoch 93/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 64ms/step - accuracy: 0.3348 - loss: 3.3442 - val_accuracy: 0.0987 - val_loss: 8.2658
Epoch 94/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.3366 - loss: 3.3311 - val_accuracy: 0.1011 - val_loss: 8.2943
Epoch 95/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 58ms/step - accuracy: 0.3389 - loss: 3.3187 - val_accuracy: 0.0997 - val_loss: 8.3139
Epoch 96/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.3409 - loss: 3.3060 - val_accuracy: 0.1009 - val_loss: 8.3297
Epoch 97/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 68ms/step - accuracy: 0.3425 - loss: 3.2941 - val_accuracy: 0.0988 - val_loss: 8.3576
Epoch 98/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 69ms/step - accuracy: 0.3446 - loss: 3.2819 - val_accuracy: 0.0986 - val_loss: 8.3730
Epoch 99/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 56ms/step - accuracy: 0.3462 - loss: 3.2689 - val_accuracy: 0.0992 - val_loss: 8.3974
Epoch 100/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 22s 60ms/step - accuracy: 0.3492 - loss: 3.2576 - val_accuracy: 0.0995 - val_loss: 8.4202

In [29]:
model2.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model Creation and Training for GRU.

In [30]:
input_layer3= Input(shape= (max_length,), dtype= "int32", name= "Input_Layer3")
embedding_layer3= Embedding(input_dim= vocab_size, output_dim= embed_dim, mask_zero= False, name= "Embedding_Layer3")(input_layer3)

In [31]:
rnn3= GRU(units= rnn_units, return_sequences= False, return_state= False, name= "GRU_Layer")
embedding_layer_last3= rnn3(embedding_layer3)
output_layer3= Dense(units= vocab_size, activation= "softmax", name= "Output_Layer3")(embedding_layer_last3)

In [32]:
model3= Model(inputs= input_layer3, outputs= output_layer3)

In [33]:
model3.compile(optimizer= "adam", loss= "categorical_crossentropy", metrics= ["accuracy"])

In [34]:
model3.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Input_Layer3 (InputLayer)       │ (None, 745)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Embedding_Layer3 (Embedding)    │ (None, 745, 32)        │       320,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ GRU_Layer (GRU)                 │ (None, 64)             │        18,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer3 (Dense)           │ (None, 10000)          │       650,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 988,816 (3.77 MB)

 Trainable params: 988,816 (3.77 MB)

 Non-trainable params: 0 (0.00 B)

In [35]:
gru_model= model3.fit(X_pad, y_encoded, epochs= 100, batch_size= 256, validation_split= 0.2, verbose= 1)

Epoch 1/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 62ms/step - accuracy: 0.0382 - loss: 6.9896 - val_accuracy: 0.0373 - val_loss: 6.6979
Epoch 2/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.0397 - loss: 6.4746 - val_accuracy: 0.0472 - val_loss: 6.6297
Epoch 3/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.0561 - loss: 6.2576 - val_accuracy: 0.0670 - val_loss: 6.5100
Epoch 4/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.0742 - loss: 6.0738 - val_accuracy: 0.0822 - val_loss: 6.4454
Epoch 5/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - accuracy: 0.0892 - loss: 5.9301 - val_accuracy: 0.0883 - val_loss: 6.4181
Epoch 6/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - accuracy: 0.0967 - loss: 5.8072 - val_accuracy: 0.0899 - val_loss: 6.3974
Epoch 7/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.1050 - loss: 5.6973 - val_accuracy: 0.0933 - val_loss: 6.3866
Epoch 8/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.1113 - loss: 5.5953 - val_accuracy: 0.0965 - val_loss: 6.3705
Epoch 9/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 54ms/step - accuracy: 0.1176 - loss: 5.4933 - val_accuracy: 0.1000 - val_loss: 6.3580
Epoch 10/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1248 - loss: 5.3945 - val_accuracy: 0.1032 - val_loss: 6.3661
Epoch 11/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 65ms/step - accuracy: 0.1298 - loss: 5.3010 - val_accuracy: 0.1046 - val_loss: 6.3603
Epoch 12/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1346 - loss: 5.2129 - val_accuracy: 0.1060 - val_loss: 6.3516
Epoch 13/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.1379 - loss: 5.1297 - val_accuracy: 0.1082 - val_loss: 6.3713
Epoch 14/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.1416 - loss: 5.0514 - val_accuracy: 0.1065 - val_loss: 6.3763
Epoch 15/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.1470 - loss: 4.9744 - val_accuracy: 0.1073 - val_loss: 6.3969
Epoch 16/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 54ms/step - accuracy: 0.1508 - loss: 4.9020 - val_accuracy: 0.1098 - val_loss: 6.4111
Epoch 17/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 54ms/step - accuracy: 0.1543 - loss: 4.8315 - val_accuracy: 0.1097 - val_loss: 6.4374
Epoch 18/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.1583 - loss: 4.7623 - val_accuracy: 0.1102 - val_loss: 6.4526
Epoch 19/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - accuracy: 0.1620 - loss: 4.6949 - val_accuracy: 0.1096 - val_loss: 6.4871
Epoch 20/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 53ms/step - accuracy: 0.1673 - loss: 4.6287 - val_accuracy: 0.1105 - val_loss: 6.4999
Epoch 21/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.1729 - loss: 4.5635 - val_accuracy: 0.1111 - val_loss: 6.5347
Epoch 22/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.1777 - loss: 4.4995 - val_accuracy: 0.1106 - val_loss: 6.5533
Epoch 23/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.1845 - loss: 4.4371 - val_accuracy: 0.1095 - val_loss: 6.5788
Epoch 24/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.1904 - loss: 4.3748 - val_accuracy: 0.1090 - val_loss: 6.6075
Epoch 25/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.1975 - loss: 4.3154 - val_accuracy: 0.1107 - val_loss: 6.6351
Epoch 26/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 65ms/step - accuracy: 0.2040 - loss: 4.2570 - val_accuracy: 0.1083 - val_loss: 6.6634
Epoch 27/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 63ms/step - accuracy: 0.2110 - loss: 4.2010 - val_accuracy: 0.1078 - val_loss: 6.6971
Epoch 28/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.2179 - loss: 4.1455 - val_accuracy: 0.1058 - val_loss: 6.7260
Epoch 29/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 61ms/step - accuracy: 0.2257 - loss: 4.0925 - val_accuracy: 0.1074 - val_loss: 6.7501
Epoch 30/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 64ms/step - accuracy: 0.2317 - loss: 4.0403 - val_accuracy: 0.1070 - val_loss: 6.7790
Epoch 31/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 64ms/step - accuracy: 0.2389 - loss: 3.9905 - val_accuracy: 0.1065 - val_loss: 6.8132
Epoch 32/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.2464 - loss: 3.9422 - val_accuracy: 0.1055 - val_loss: 6.8373
Epoch 33/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 66ms/step - accuracy: 0.2526 - loss: 3.8958 - val_accuracy: 0.1036 - val_loss: 6.8687
Epoch 34/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 65ms/step - accuracy: 0.2586 - loss: 3.8504 - val_accuracy: 0.1073 - val_loss: 6.9031
Epoch 35/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.2660 - loss: 3.8059 - val_accuracy: 0.1044 - val_loss: 6.9305
Epoch 36/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.2725 - loss: 3.7643 - val_accuracy: 0.1043 - val_loss: 6.9560
Epoch 37/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.2788 - loss: 3.7234 - val_accuracy: 0.1051 - val_loss: 6.9886
Epoch 38/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.2839 - loss: 3.6844 - val_accuracy: 0.1046 - val_loss: 7.0100
Epoch 39/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.2908 - loss: 3.6461 - val_accuracy: 0.1047 - val_loss: 7.0408
Epoch 40/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 23s 61ms/step - accuracy: 0.2954 - loss: 3.6092 - val_accuracy: 0.1034 - val_loss: 7.0681
Epoch 41/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 68ms/step - accuracy: 0.3011 - loss: 3.5739 - val_accuracy: 0.1031 - val_loss: 7.0973
Epoch 42/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 66ms/step - accuracy: 0.3053 - loss: 3.5392 - val_accuracy: 0.1033 - val_loss: 7.1215
Epoch 43/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.3113 - loss: 3.5062 - val_accuracy: 0.1025 - val_loss: 7.1549
Epoch 44/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.3155 - loss: 3.4744 - val_accuracy: 0.1030 - val_loss: 7.1795
Epoch 45/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.3213 - loss: 3.4437 - val_accuracy: 0.1014 - val_loss: 7.1953
Epoch 46/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.3253 - loss: 3.4142 - val_accuracy: 0.1010 - val_loss: 7.2250
Epoch 47/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 67ms/step - accuracy: 0.3294 - loss: 3.3836 - val_accuracy: 0.1006 - val_loss: 7.2533
Epoch 48/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 54ms/step - accuracy: 0.3345 - loss: 3.3565 - val_accuracy: 0.1024 - val_loss: 7.2816
Epoch 49/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - accuracy: 0.3384 - loss: 3.3293 - val_accuracy: 0.0993 - val_loss: 7.2958
Epoch 50/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.3427 - loss: 3.3020 - val_accuracy: 0.1006 - val_loss: 7.3186
Epoch 51/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.3473 - loss: 3.2771 - val_accuracy: 0.0994 - val_loss: 7.3458
Epoch 52/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.3516 - loss: 3.2511 - val_accuracy: 0.0995 - val_loss: 7.3746
Epoch 53/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 66ms/step - accuracy: 0.3554 - loss: 3.2285 - val_accuracy: 0.0994 - val_loss: 7.3978
Epoch 54/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 64ms/step - accuracy: 0.3583 - loss: 3.2051 - val_accuracy: 0.0990 - val_loss: 7.4094
Epoch 55/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.3633 - loss: 3.1822 - val_accuracy: 0.0990 - val_loss: 7.4452
Epoch 56/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.3660 - loss: 3.1602 - val_accuracy: 0.0988 - val_loss: 7.4670
Epoch 57/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.3688 - loss: 3.1377 - val_accuracy: 0.0971 - val_loss: 7.4922
Epoch 58/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.3717 - loss: 3.1172 - val_accuracy: 0.0960 - val_loss: 7.5120
Epoch 59/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 71ms/step - accuracy: 0.3753 - loss: 3.0975 - val_accuracy: 0.0955 - val_loss: 7.5324
Epoch 60/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 66ms/step - accuracy: 0.3786 - loss: 3.0783 - val_accuracy: 0.0970 - val_loss: 7.5543
Epoch 61/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 61ms/step - accuracy: 0.3819 - loss: 3.0606 - val_accuracy: 0.0920 - val_loss: 7.6458
Epoch 62/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - accuracy: 0.3834 - loss: 3.0459 - val_accuracy: 0.0948 - val_loss: 7.6009
Epoch 63/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 54ms/step - accuracy: 0.3879 - loss: 3.0233 - val_accuracy: 0.0948 - val_loss: 7.6226
Epoch 64/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.3899 - loss: 3.0041 - val_accuracy: 0.0951 - val_loss: 7.6477
Epoch 65/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.3934 - loss: 2.9875 - val_accuracy: 0.0944 - val_loss: 7.6667
Epoch 66/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - accuracy: 0.3957 - loss: 2.9697 - val_accuracy: 0.0942 - val_loss: 7.6877
Epoch 67/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 63ms/step - accuracy: 0.3978 - loss: 2.9525 - val_accuracy: 0.0946 - val_loss: 7.7090
Epoch 68/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.4004 - loss: 2.9385 - val_accuracy: 0.0941 - val_loss: 7.7343
Epoch 69/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - accuracy: 0.4033 - loss: 2.9212 - val_accuracy: 0.0938 - val_loss: 7.7492
Epoch 70/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.4053 - loss: 2.9075 - val_accuracy: 0.0928 - val_loss: 7.7727
Epoch 71/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.4074 - loss: 2.8916 - val_accuracy: 0.0945 - val_loss: 7.7930
Epoch 72/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.4101 - loss: 2.8785 - val_accuracy: 0.0910 - val_loss: 7.8088
Epoch 73/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - accuracy: 0.4109 - loss: 2.8695 - val_accuracy: 0.0925 - val_loss: 7.8338
Epoch 74/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.4156 - loss: 2.8495 - val_accuracy: 0.0918 - val_loss: 7.8586
Epoch 75/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.4185 - loss: 2.8354 - val_accuracy: 0.0920 - val_loss: 7.8680
Epoch 76/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.4196 - loss: 2.8223 - val_accuracy: 0.0906 - val_loss: 7.8895
Epoch 77/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 54ms/step - accuracy: 0.4220 - loss: 2.8104 - val_accuracy: 0.0904 - val_loss: 7.9011
Epoch 78/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 59ms/step - accuracy: 0.4236 - loss: 2.7970 - val_accuracy: 0.0900 - val_loss: 7.9288
Epoch 79/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 63ms/step - accuracy: 0.4247 - loss: 2.7856 - val_accuracy: 0.0892 - val_loss: 7.9503
Epoch 80/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 69ms/step - accuracy: 0.4286 - loss: 2.7724 - val_accuracy: 0.0899 - val_loss: 7.9650
Epoch 81/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.4301 - loss: 2.7598 - val_accuracy: 0.0891 - val_loss: 7.9826
Epoch 82/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.4317 - loss: 2.7502 - val_accuracy: 0.0881 - val_loss: 8.0058
Epoch 83/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 68ms/step - accuracy: 0.4340 - loss: 2.7378 - val_accuracy: 0.0889 - val_loss: 8.0268
Epoch 84/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - accuracy: 0.4353 - loss: 2.7266 - val_accuracy: 0.0888 - val_loss: 8.0432
Epoch 85/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.4358 - loss: 2.7199 - val_accuracy: 0.0884 - val_loss: 8.0589
Epoch 86/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 56ms/step - accuracy: 0.4390 - loss: 2.7043 - val_accuracy: 0.0872 - val_loss: 8.0777
Epoch 87/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.4415 - loss: 2.6928 - val_accuracy: 0.0886 - val_loss: 8.0926
Epoch 88/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - accuracy: 0.4423 - loss: 2.6851 - val_accuracy: 0.0878 - val_loss: 8.1193
Epoch 89/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 76ms/step - accuracy: 0.4431 - loss: 2.6733 - val_accuracy: 0.0885 - val_loss: 8.1382
Epoch 90/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - accuracy: 0.4466 - loss: 2.6669 - val_accuracy: 0.0875 - val_loss: 8.1511
Epoch 91/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 21s 55ms/step - accuracy: 0.4482 - loss: 2.6547 - val_accuracy: 0.0872 - val_loss: 8.1733
Epoch 92/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 57ms/step - accuracy: 0.4492 - loss: 2.6426 - val_accuracy: 0.0868 - val_loss: 8.1905
Epoch 93/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.4505 - loss: 2.6343 - val_accuracy: 0.0871 - val_loss: 8.1966
Epoch 94/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 20s 54ms/step - accuracy: 0.4515 - loss: 2.6284 - val_accuracy: 0.0854 - val_loss: 8.2233
Epoch 95/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.4537 - loss: 2.6181 - val_accuracy: 0.0858 - val_loss: 8.2401
Epoch 96/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 16s 61ms/step - accuracy: 0.4555 - loss: 2.6096 - val_accuracy: 0.0851 - val_loss: 8.2621
Epoch 97/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 17s 63ms/step - accuracy: 0.4577 - loss: 2.5975 - val_accuracy: 0.0862 - val_loss: 8.2744
Epoch 98/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 18s 54ms/step - accuracy: 0.4598 - loss: 2.5878 - val_accuracy: 0.0856 - val_loss: 8.2974
Epoch 99/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - accuracy: 0.4608 - loss: 2.5807 - val_accuracy: 0.0853 - val_loss: 8.3054
Epoch 100/100
266/266 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - accuracy: 0.4623 - loss: 2.5711 - val_accuracy: 0.0854 - val_loss: 8.3261

In [36]:
model3.save('gru_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Apply the trained model from H5 file

In [37]:
index_to_word= {}
for word, index in word_index.items():
    index_to_word[index]= word

In [60]:
def predictor(model, tokenizer, text, max_length):
    text= text.lower()
    seq= tokenizer.texts_to_sequences([text]) [0]
    seq= pad_sequences([seq], maxlen= max_length, padding= "pre")
    pred= model.predict(seq, verbose=1)
    pred_index= np.argmax(pred, axis= -1) [0]
    return index_to_word.get(pred_index, "")

In [61]:
seed_text= "you will"
next_word= predictor(model, tokenizer, seed_text, max_length)
print(next_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
driven

In [62]:
seed_text= "you will"
next_word= predictor(model2, tokenizer, seed_text, max_length)
print(next_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
be

In [63]:
seed_text= "you will"
next_word= predictor(model3, tokenizer, seed_text, max_length)
print(next_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
not

Predict a whole sentence from a word

In [64]:
def generate_text(model, tokenizer, seed_text, max_length, num_words):
    for _ in range(num_words):
        next_word= predictor(model, tokenizer, seed_text, max_length)
        if next_word == "":
          break
        seed_text += " " + next_word
    return seed_text

In [65]:
seed_text= "the meaning of life"
generated_text= generate_text(model, tokenizer, seed_text, max_length, 10)
print(generated_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
the meaning of life anytime oncerequited faced

In [66]:
seed_text= "the meaning of life"
generated_text= generate_text(model2, tokenizer, seed_text, max_length, 10)
print(generated_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
the meaning of life is to be a good book is a good piece

In [67]:
seed_text= "the meaning of life"
generated_text= generate_text(model3, tokenizer, seed_text, max_length, 10)
print(generated_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
the meaning of life is the cosmic perspective that you can afford to be

Now, I will use a model in an User Interface (UI) i.e. Model Deployment.

For this I will use pickle file.

In [75]:
import pickle

In [76]:
with open('tokenizer.pickle', 'wb') as f:
    pickle.dump(tokenizer, f)

In [77]:
with open("max_length.pickle", "wb") as f:
    pickle.dump(max_length, f)

Now, I will create an app for next word prediction, from .py file in VS Code.

Since, the accuracy from GRU is higher, I will use it's .h5 file to create UI.